{{- if .Values.apipark.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apipark.fullname" . }}
  labels:
    {{- include "apipark.labels" . | nindent 4 }}
    app.kubernetes.io/component: apipark
spec:
  replicas: {{ .Values.apipark.replicaCount }}
  selector:
    matchLabels:
      {{- include "apipark.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: apipark
  template:
    metadata:
      labels:
        {{- include "apipark.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: apipark
    spec:
      initContainers:
        - name: wait-mysql
          image: "{{ .Values.global.imageRegistry }}busybox"
          command: ['sh', '-c', 'until nc -z apipark-mysql 3306; do echo waiting for mysql; sleep 2; done;']
        - name: wait-redis
          image: "{{ .Values.global.imageRegistry }}busybox"
          command: ['sh', '-c', 'until nc -z apipark-redis 6379; do echo waiting for redis; sleep 2; done;']
        - name: wait-influxdb
          image: "{{ .Values.global.imageRegistry }}busybox"
          command: ['sh', '-c', 'until nc -z apipark-influxdb 8086; do echo waiting for redis; sleep 2; done;']
        - name: wait-apinto
          image: "{{ .Values.global.imageRegistry }}busybox"
          command: ['sh', '-c', 'until nc -z apipark-apinto 9400; do echo waiting for redis; sleep 2; done;']
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # serviceAccountName: {{ include "apipark.serviceAccountName" . }}
      containers:
        - name: apipark
          image: "{{ .Values.global.imageRegistry }}{{ .Values.apipark.image.repository }}:{{ .Values.apipark.image.tag }}"
          imagePullPolicy: {{ .Values.apipark.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.apipark.service.port }}
              protocol: TCP
          env:
            - name: MYSQL_USER_NAME
              value: {{ .Values.apipark.env.MYSQL_USER_NAME | quote }}
            - name: MYSQL_PWD
              value: {{ .Values.apipark.env.MYSQL_PWD | quote }}
            - name: MYSQL_IP
              value: {{ .Values.apipark.env.MYSQL_IP | quote }}
            - name: MYSQL_PORT
              value: {{ .Values.apipark.env.MYSQL_PORT | quote }}
            - name: MYSQL_DB
              value: {{ .Values.apipark.env.MYSQL_DB | quote }}
            - name: ERROR_DIR
              value: {{ .Values.apipark.env.ERROR_DIR | quote }}
            - name: ERROR_FILE_NAME
              value: {{ .Values.apipark.env.ERROR_FILE_NAME | quote }}
            - name: ERROR_LOG_LEVEL
              value: {{ .Values.apipark.env.ERROR_LOG_LEVEL | quote }}
            - name: ERROR_EXPIRE
              value: {{ .Values.apipark.env.ERROR_EXPIRE | quote }}
            - name: ERROR_PERIOD
              value: {{ .Values.apipark.env.ERROR_PERIOD | quote }}
            - name: REDIS_ADDR
              value: {{ .Values.apipark.env.REDIS_ADDR | quote }}
            - name: REDIS_PWD
              value: {{ .Values.apipark.env.REDIS_PWD | quote }}
            - name: ADMIN_PASSWORD
              value: {{ .Values.apipark.env.ADMIN_PASSWORD | quote }}
            - name: Init
              value: {{ .Values.apipark.env.Init | quote }}
            - name: InfluxdbToken
              value: {{ .Values.apipark.env.InfluxdbToken | quote }}
          {{- with .Values.apipark.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
