{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apipark.grafana.fullname" . }}
  labels:
    {{- include "apipark.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "apipark.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: grafana
  template:
    metadata:
      labels:
        {{- include "apipark.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: grafana
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: grafana
          image: "{{ .Values.global.imageRegistry }}{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          command:
            - sh
            - -euc
            - |
              mkdir -p /etc/grafana/provisioning/datasources
              cp /etc/grafana-config/grafana-datasource.yaml /etc/grafana/provisioning/datasources/ds.yaml
              /run.sh
          ports:
            - name: grafana
              containerPort: {{ .Values.grafana.service.port }}
              protocol: TCP
          env:
            - name: GF_PATHS_PROVISIONING
              value: "/etc/grafana/provisioning"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: {{ .Values.grafana.auth.anonymousEnabled | quote }}
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: {{ .Values.grafana.auth.anonymousOrgRole | quote }}
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
            - name: grafana-config
              mountPath: /etc/grafana-config
          {{- with .Values.grafana.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: grafana-data
          {{- if .Values.grafana.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "apipark.grafana.fullname" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: grafana-config
          configMap:
            name: {{ include "apipark.grafana.fullname" . }}-config
{{- end }}
